export const S = {
  page: { padding: "32px 40px", maxWidth: 1000, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
  toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, background: "#7ec87e", maxWidth: 340 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 32 },
  heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 30, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
  sub: { fontSize: 13, color: "#aaa" },
  saOnly: { fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", padding: "5px 12px", background: "#C9A96E18", color: "#C9A96E", border: "1px solid #C9A96E44", borderRadius: 4, fontWeight: 500, flexShrink: 0 },
  section: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "24px", marginBottom: 20 },
  sectionTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 20, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
  sectionSub: { fontSize: 12, color: "#aaa", marginBottom: 20 },
  flagsGrid: { display: "flex", flexDirection: "column", gap: 0 },
  flagRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, padding: "14px 0", borderBottom: "1px solid #f5f5f2" },
  flagLabel: { fontSize: 13, fontWeight: 400, color: "#1a1208", marginBottom: 2 },
  flagDesc: { fontSize: 11, color: "#bbb" },
  toggleWrap: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 },
  savingDot: { fontSize: 11, color: "#bbb" },
  toggle: { width: 38, height: 22, borderRadius: 11, border: "none", cursor: "pointer", position: "relative", transition: "background .2s", flexShrink: 0 },
  toggleThumb: { position: "absolute", top: 2, width: 18, height: 18, borderRadius: "50%", background: "#fff", transition: "transform .2s", boxShadow: "0 1px 4px rgba(0,0,0,.2)" },
  integGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  integCard: { border: "1.5px solid #ededea", borderRadius: 8, padding: "16px" },
  integTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  integLabel: { fontSize: 13, fontWeight: 500, color: "#1a1208" },
  integStatus: { fontSize: 9, letterSpacing: ".08em", textTransform: "uppercase", padding: "3px 8px", borderRadius: 3, fontWeight: 600 },
  integDetail: { fontSize: 11, color: "#aaa", marginBottom: 4, fontFamily: "monospace" },
  integBtn: { fontSize: 10, letterSpacing: ".06em", textTransform: "uppercase", padding: "6px 14px", border: "1.5px solid #e8e8e4", borderRadius: 5, background: "#fff", cursor: "pointer", marginTop: 8, color: "#555" },
  empty: { textAlign: "center", padding: "60px 0", fontSize: 13, color: "#bbb" },
};
