export const S = {
  page:    { padding:"32px 40px",maxWidth:1100,margin:"0 auto",fontFamily:"'DM Sans',sans-serif" },
  toast:   { position:"fixed",top:20,right:20,zIndex:999,padding:"12px 20px",borderRadius:8,color:"#fff",fontSize:13,fontWeight:500 },
  header:  { display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24 },
  heading: { fontFamily:"'Cormorant Garamond',serif",fontSize:30,fontWeight:400,color:"#1a1208",marginBottom:4 },
  sub:     { fontSize:13,color:"#aaa" },
  newBtn:  { fontSize:11,letterSpacing:".1em",textTransform:"uppercase",padding:"10px 20px",background:"#1a1208",color:"#F0E8D6",border:"none",borderRadius:6,cursor:"pointer",fontWeight:500 },
  overlay: { position:"fixed",inset:0,background:"rgba(0,0,0,.45)",zIndex:500,display:"flex",alignItems:"center",justifyContent:"center" },
  modal:   { background:"#fff",borderRadius:12,padding:"28px 32px",width:"100%",maxWidth:500,maxHeight:"90vh",overflowY:"auto" },
  modalTitle:{ fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,color:"#1a1208",marginBottom:20 },
  label:   { display:"block",fontSize:10,letterSpacing:".1em",textTransform:"uppercase",color:"#aaa",marginBottom:6 },
  input:   { width:"100%",fontSize:13,padding:"9px 12px",border:"1.5px solid #e8e8e4",borderRadius:8,outline:"none",fontFamily:"'DM Sans',sans-serif" },
  select:  { width:"100%",fontSize:13,padding:"9px 12px",border:"1.5px solid #e8e8e4",borderRadius:8,outline:"none",background:"#fff",fontFamily:"'DM Sans',sans-serif" },
  cancelBtn:{ fontSize:11,padding:"9px 18px",border:"1.5px solid #e8e8e4",borderRadius:6,background:"#fff",color:"#555",cursor:"pointer" },
  saveBtn:  { fontSize:11,padding:"9px 20px",background:"#1a1208",color:"#F0E8D6",border:"none",borderRadius:6,cursor:"pointer",fontWeight:500 },
  table:   { background:"#fff",border:"1.5px solid #ededea",borderRadius:10,overflow:"hidden" },
  thead:   { display:"flex",gap:16,padding:"10px 16px",background:"#fafaf8",borderBottom:"1px solid #ededea",fontSize:10,letterSpacing:".1em",textTransform:"uppercase",color:"#aaa",alignItems:"center" },
  trow:    { display:"flex",gap:16,padding:"14px 16px",borderBottom:"1px solid #f5f5f2",alignItems:"center" },
  productName:{ fontSize:13,fontWeight:400,color:"#1a1208",marginBottom:2 },
  productDesc:{ fontSize:11,color:"#bbb" },
  typePill:{ fontSize:9,letterSpacing:".1em",textTransform:"uppercase",padding:"3px 8px",borderRadius:4,fontWeight:600,whiteSpace:"nowrap" },
  cell:    { fontSize:12,color:"#555" },
  statusPill:{ fontSize:9,letterSpacing:".1em",textTransform:"uppercase",padding:"3px 8px",borderRadius:4,fontWeight:600 },
  actionBtn:{ fontSize:10,padding:"5px 10px",border:"1.5px solid #e8e8e4",borderRadius:5,background:"#fff",cursor:"pointer",color:"#555" },
  empty:   { textAlign:"center",padding:"60px 0",fontSize:13,color:"#bbb" },
};
