export const S = {
    page: { padding: "32px 40px", maxWidth: 1300, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
    toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, boxShadow: "0 4px 20px rgba(0,0,0,.15)" },
    header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 },
    heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 30, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
    sub: { fontSize: 13, color: "#aaa", maxWidth: 600 },
    liveNote: { fontSize: 11, color: "#7ec87e", fontWeight: 500 },
    newBtn: { fontSize: 11, letterSpacing: ".1em", textTransform: "uppercase", padding: "10px 20px", border: "none", borderRadius: 6, fontWeight: 600, textDecoration: "none", cursor: "pointer" },
    readOnlyBanner: { background: "#7ec87e18", border: "1px solid #7ec87e44", borderRadius: 8, padding: "10px 16px", fontSize: 12, color: "#3a7c3a", marginBottom: 16 },
    filters: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap", alignItems: "center" },
    search: { fontSize: 12, padding: "8px 14px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", width: 220, fontFamily: "'DM Sans',sans-serif" },
    select: { fontSize: 12, padding: "8px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", background: "#fff", fontFamily: "'DM Sans',sans-serif", cursor: "pointer" },
    bulkBar: { display: "flex", alignItems: "center", gap: 8, padding: "6px 12px", background: "#1a1208", borderRadius: 8 },
    bulkCount: { fontSize: 11, color: "#F0E8D6", fontWeight: 500 },
    bulkBtn: { fontSize: 11, background: "none", border: "none", color: "#F0E8D6", cursor: "pointer", letterSpacing: ".04em" },
    table: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, overflow: "hidden" },
    thead: { display: "flex", alignItems: "center", padding: "10px 16px", background: "#fafaf8", borderBottom: "1px solid #ededea", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#aaa", gap: 8 },
    trow: { display: "flex", alignItems: "center", padding: "12px 16px", borderBottom: "1px solid #f5f5f2", transition: "background .1s", gap: 8 },
    tempty: { padding: "40px 0", textAlign: "center", fontSize: 13, color: "#bbb" },
    topicTitle: { display: "block", fontSize: 13, fontWeight: 400, color: "#1a1208", marginBottom: 2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    topicMeta: { display: "block", fontSize: 10, color: "#bbb" },
    statusPill: { fontSize: 9, letterSpacing: ".1em", textTransform: "uppercase", padding: "3px 8px", borderRadius: 4, fontWeight: 600 },
    actionBtn: { fontSize: 10, padding: "4px 10px", border: "1.5px solid #e8e8e4", borderRadius: 5, background: "#fff", cursor: "pointer", color: "#555", textDecoration: "none", letterSpacing: ".03em", whiteSpace: "nowrap" },
    foot: { padding: "10px 16px", fontSize: 11, color: "#bbb", display: "flex", justifyContent: "space-between", marginTop: 4 },
};