// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({ children }) {
// // //   return (
// // //     <html
// // //       lang="en"
// // //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// // //     >
// // //       <body className="min-h-full flex flex-col">{children}</body>
// // //     </html>
// // //   );
// // // }

// // // app/layout.js — ROOT layout (html + body only)
// // import { Geist, Geist_Mono } from 'next/font/google';
// // import './globals.css';
// // import Providers from '@/providers/Providers';

// // const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
// // const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

// // export const metadata = {
// //   title:       'Fameo — Creator Platform',
// //   description: 'Discover top Indian creators. Premium gear, resources, and community.',
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// //         <Providers>
// //           {children}
// //         </Providers>
// //       </body>
// //     </html>
// //   );
// // }

// // app/layout.js
// import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';
// import Providers from '@/providers/Providers';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   metadataBase: new URL('https://fameo.vip'),

//   title: {
//     default: 'Fameo — For Fame & Recognition ',
//     template: '%s | Fameo',
//   },

//   description:
//     'Fameo is an exclusive verified community for creators, influencers, celebrities, athletes, politicians, and recognised public figures. Connect with authentic, verified individuals in a trusted platform built for meaningful networking and recognition',

//   keywords: [
//     'Fameo',
//     'Creator Platform',
//     'Influencers',
//     'Content Creators',
//     'India Creators',
//   ],

//   icons: {
//     icon: '/favicon.ico',
//     apple: '/apple-icon.png',
//   },

//   openGraph: {
//     title: 'Fameo — Creator Platform',
//     description:
//       'Discover top Indian creators. Premium gear, resources, and community.',
//     images: ['/og-image.jpg'],
//   },

//   twitter: {
//     card: 'summary_large_image',
//     images: ['/og-image.jpg'],
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }



// app/layout.js
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from '@/providers/Providers';
 
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
 
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
 
export const metadata = {
  // Every relative OG / Twitter image below is resolved against this. It was
  // still the create-next-app placeholder ('https://yourdomain.com'), so every
  // share card pointed at a domain that isn't ours.
  metadataBase: new URL('https://fameo.vip'),
 
  title: {
    default: 'Fameo — For Fame & Recognition ',
    template: '%s | Fameo',
  },
 
  description:
    'Fameo is an exclusive verified community for creators, influencers, celebrities, athletes, politicians, and recognised public figures. Connect with authentic, verified individuals in a trusted platform built for meaningful networking and recognition',
 
  keywords: [
    'Fameo',
    'Creator Platform',
    'Influencers',
    'Content Creators',
    'India Creators',
  ],
 
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-icon.png',
  },
 
  openGraph: {
    title: 'Fameo — Creator Platform',
    description:
      'Discover top Indian creators. Premium gear, resources, and community.',
    images: ['/og-image.jpg'],
  },
 
  twitter: {
    card: 'summary_large_image',
    images: ['/og-image.jpg'],
  },
};
 
// Next injects `width=device-width, initial-scale=1` by default, but not
// viewportFit — without it the fixed nav sits under the notch in landscape on
// iPhones, and the safe-area-inset values MainNav reads all resolve to 0.
// themeColor tints the browser chrome to match the dark hero.
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: '#150520',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
 