export const S = {
  page: { padding: "32px 40px", maxWidth: 1200, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
  toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, boxShadow: "0 4px 20px rgba(0,0,0,.15)" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 },
  heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 30, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
  sub: { fontSize: 13, color: "#aaa" },
  tabRow: { display: "flex", borderBottom: "1px solid #ededea", marginBottom: 20 },
  tabBtn: { fontSize: 12, padding: "10px 18px", border: "none", background: "transparent", cursor: "pointer", fontFamily: "'DM Sans',sans-serif", transition: "all .15s" },
  filters: { display: "flex", gap: 10, marginBottom: 16 },
  search: { fontSize: 12, padding: "8px 14px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", fontFamily: "'DM Sans',sans-serif" },
  select: { fontSize: 12, padding: "8px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", background: "#fff", cursor: "pointer", fontFamily: "'DM Sans',sans-serif" },
  layout: { display: "grid", gridTemplateColumns: "300px 1fr", gap: 16, height: "calc(100vh - 300px)", minHeight: 500 },
  ticketList: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, overflow: "auto" },
  ticket: { padding: "12px 14px", borderBottom: "1px solid #f5f5f2", cursor: "pointer", transition: "background .1s", borderLeft: "3px solid transparent" },
  ticketTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 },
  ticketSubject: { fontSize: 12, fontWeight: 500, color: "#1a1208", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", flex: 1, marginRight: 8 },
  priorityDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
  ticketMeta: { fontSize: 10, color: "#bbb", marginBottom: 4 },
  statusBadge: { fontSize: 9, letterSpacing: ".08em", textTransform: "uppercase", padding: "2px 7px", borderRadius: 3, fontWeight: 600 },
  empty: { textAlign: "center", padding: "40px 0", fontSize: 13, color: "#bbb" },
  ticketDetail: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "20px", display: "flex", flexDirection: "column", overflow: "auto" },
  emptyDetail: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", fontSize: 13, color: "#bbb", gap: 8 },
  detailHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16, gap: 16, flexWrap: "wrap" },
  detailTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 22, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
  detailMeta: { fontSize: 12, color: "#aaa" },
  inProgressBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #C9A96E44", background: "#C9A96E18", color: "#7a5a1a", borderRadius: 6, cursor: "pointer" },
  resolveBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #7ec87e44", background: "#7ec87e18", color: "#3a7c3a", borderRadius: 6, cursor: "pointer", fontWeight: 500 },
  closeBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #e8e8e4", background: "#fff", color: "#888", borderRadius: 6, cursor: "pointer" },
  messages: { flex: 1, overflow: "auto", display: "flex", flexDirection: "column", gap: 10, padding: "12px 0", marginBottom: 12 },
  message: { display: "flex", flexDirection: "column", maxWidth: "75%", gap: 3 },
  messageBubble: { padding: "10px 14px", borderRadius: 10, fontSize: 13, lineHeight: 1.5 },
  messageTime: { fontSize: 10, color: "#bbb" },
  replyBox: { borderTop: "1px solid #ededea", paddingTop: 12, flexShrink: 0 },
  replyInput: { width: "100%", fontSize: 13, padding: "10px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", resize: "none", fontFamily: "'DM Sans',sans-serif" },
  replyBtn: { fontSize: 11, padding: "9px 20px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 500 },
  lookupSection: { maxWidth: 700 },
  lookupBtn: { fontSize: 12, padding: "8px 20px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 8, cursor: "pointer", fontWeight: 500 },
  learnerCard: { display: "flex", alignItems: "center", gap: 14, padding: "14px 16px", background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, marginBottom: 10 },
  learnerAvatar: { width: 36, height: 36, borderRadius: "50%", background: "#C9A96E22", color: "#C9A96E", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 600, flexShrink: 0 },
  learnerName: { fontSize: 13, fontWeight: 500, color: "#1a1208", marginBottom: 2 },
  learnerEmail: { fontSize: 11, color: "#888" },
  learnerStat: { fontSize: 10, color: "#bbb" },
  ticketForLearnerBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #e8e8e4", borderRadius: 6, background: "#fff", cursor: "pointer", color: "#555", flexShrink: 0 },
  faqSection: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 },
  sectionTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 18, fontWeight: 400, color: "#1a1208", marginBottom: 14 },
  faqForm: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "20px" },
  faqList: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "20px", overflowY: "auto", maxHeight: 600 },
  label: { display: "block", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#aaa", marginBottom: 6 },
  input: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", fontFamily: "'DM Sans',sans-serif" },
  textarea: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", resize: "vertical", fontFamily: "'DM Sans',sans-serif" },
  addFaqBtn: { marginTop: 12, fontSize: 11, letterSpacing: ".08em", textTransform: "uppercase", padding: "9px 18px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 500 },
  faqCard: { padding: "14px 0", borderBottom: "1px solid #f5f5f2" },
  faqQ: { fontSize: 12, fontWeight: 500, color: "#1a1208", marginBottom: 6 },
  faqA: { fontSize: 12, color: "#666", lineHeight: 1.5 },
  faqCategory: { display: "inline-block", marginTop: 6, fontSize: 9, letterSpacing: ".1em", textTransform: "uppercase", padding: "2px 8px", borderRadius: 3, background: "#C9A96E18", color: "#C9A96E", fontWeight: 600 },
};
