export const S = {
    page: { display: "flex", flexDirection: "column", height: "100vh", fontFamily: "'DM Sans',sans-serif", overflow: "hidden" },
    toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, boxShadow: "0 4px 20px rgba(0,0,0,.15)" },
    topBar: { display: "flex", alignItems: "center", gap: 12, padding: "10px 24px", background: "#fff", borderBottom: "1px solid #ededea", flexShrink: 0 },
    backBtn: { fontSize: 12, color: "#888", background: "none", border: "none", cursor: "pointer", letterSpacing: ".04em", flexShrink: 0 },
    topMid: { flex: 1, display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
    topActions: { display: "flex", gap: 8, flexShrink: 0 },
    previewBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #e8e8e4", borderRadius: 6, background: "#fff", color: "#555", cursor: "pointer" },
    saveBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #e8e8e4", borderRadius: 6, background: "#fff", color: "#1a1208", cursor: "pointer", fontWeight: 500 },
    reviewBtn: { fontSize: 11, padding: "7px 14px", border: "1.5px solid #7eb8d844", borderRadius: 6, background: "#7eb8d818", color: "#7eb8d8", cursor: "pointer", fontWeight: 500 },
    publishBtn: { fontSize: 11, padding: "7px 16px", border: "none", borderRadius: 6, background: "#C9A96E", color: "#1a1200", cursor: "pointer", fontWeight: 600 },
    layout: { display: "grid", flex: 1, overflow: "hidden" },
    editorPane: { overflow: "auto", borderRight: "1px solid #ededea", display: "flex", flexDirection: "column" },
    tabRow: { display: "flex", padding: "0 24px", borderBottom: "1px solid #ededea", background: "#fff", flexShrink: 0 },
    tabBtn: { fontSize: 12, padding: "12px 16px", border: "none", background: "transparent", cursor: "pointer", fontFamily: "'DM Sans',sans-serif", transition: "all .15s" },
    tabBody: { padding: "20px 24px", flex: 1, overflowY: "auto" },
    titleInput: { width: "100%", fontFamily: "'Cormorant Garamond',serif", fontSize: 28, fontWeight: 400, border: "none", outline: "none", color: "#1a1208", marginBottom: 12, letterSpacing: "-.01em", background: "transparent" },
    descInput: { width: "100%", fontSize: 14, border: "1.5px solid #e8e8e4", borderRadius: 8, padding: "10px 14px", outline: "none", fontFamily: "'DM Sans',sans-serif", resize: "vertical", marginBottom: 20 },
    label: { display: "block", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#aaa", marginBottom: 8, fontWeight: 500 },
    bodyInput: { width: "100%", fontSize: 13, fontFamily: "monospace", lineHeight: 1.7, border: "1.5px solid #e8e8e4", borderRadius: 8, padding: "12px 14px", outline: "none", resize: "vertical", marginBottom: 20 },
    arrRow: { display: "flex", gap: 8, marginBottom: 6 },
    arrInput: { flex: 1, fontSize: 13, padding: "8px 12px", border: "1.5px solid #e8e8e4", borderRadius: 6, outline: "none", fontFamily: "'DM Sans',sans-serif" },
    remBtn: { fontSize: 11, padding: "4px 8px", border: "1.5px solid #e8e8e4", borderRadius: 5, background: "#fff", color: "#d49090", cursor: "pointer", flexShrink: 0 },
    addBtn: { fontSize: 11, letterSpacing: ".06em", padding: "7px 14px", border: "1.5px dashed #ddd", borderRadius: 6, background: "transparent", color: "#aaa", cursor: "pointer", marginTop: 4 },
    metaGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 },
    metaSel: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", background: "#fff", fontFamily: "'DM Sans',sans-serif" },
    metaInput: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", fontFamily: "'DM Sans',sans-serif" },
    previewPane: { overflow: "auto", padding: "32px 36px", background: "#fff" },
};