export const S = {
  page: { padding: "32px 40px", maxWidth: 1100, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
  toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, boxShadow: "0 4px 20px rgba(0,0,0,.15)" },
  header: { marginBottom: 28 },
  heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 30, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
  sub: { fontSize: 13, color: "#aaa" },
  layout: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 },
  compose: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "24px" },
  composeTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 18, fontWeight: 400, color: "#1a1208", marginBottom: 16 },
  label: { display: "block", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#aaa", marginBottom: 6 },
  input: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", fontFamily: "'DM Sans',sans-serif" },
  textarea: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", resize: "vertical", fontFamily: "'DM Sans',sans-serif" },
  select: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", background: "#fff", fontFamily: "'DM Sans',sans-serif" },
  sendBtn: { marginTop: 16, width: "100%", fontSize: 12, letterSpacing: ".08em", textTransform: "uppercase", padding: "11px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 500, transition: "opacity .2s" },
  history: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "24px", overflowY: "auto", maxHeight: 600 },
  sentCard: { padding: "14px 0", borderBottom: "1px solid #f5f5f2" },
  typeDot: { fontSize: 9, letterSpacing: ".1em", textTransform: "uppercase", padding: "2px 8px", borderRadius: 3, fontWeight: 600 },
  sentTitle: { fontSize: 13, fontWeight: 400, color: "#1a1208" },
};
