export const S = {
    page: { padding: "32px 40px", maxWidth: 900, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
    toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, background: "#7ec87e" },
    header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 },
    heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 30, fontWeight: 400, color: "#1a1208", marginBottom: 4 },
    sub: { fontSize: 13, color: "#aaa" },
    inviteBtn: { fontSize: 11, letterSpacing: ".1em", textTransform: "uppercase", padding: "10px 20px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 500 },
    overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,.45)", zIndex: 500, display: "flex", alignItems: "center", justifyContent: "center" },
    modal: { background: "#fff", borderRadius: 12, padding: "28px 32px", width: "100%", maxWidth: 480, maxHeight: "90vh", overflowY: "auto" },
    modalTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 24, fontWeight: 400, color: "#1a1208", marginBottom: 20 },
    label: { display: "block", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#aaa", marginBottom: 6 },
    input: { width: "100%", fontSize: 13, padding: "9px 12px", border: "1.5px solid #e8e8e4", borderRadius: 8, outline: "none", fontFamily: "'DM Sans',sans-serif" },
    modGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 4 },
    modCheck: { display: "flex", alignItems: "center", gap: 6, cursor: "pointer" },
    cancelBtn: { fontSize: 11, padding: "9px 18px", border: "1.5px solid #e8e8e4", borderRadius: 6, background: "#fff", color: "#555", cursor: "pointer" },
    saveBtn: { fontSize: 11, padding: "9px 20px", background: "#1a1208", color: "#F0E8D6", border: "none", borderRadius: 6, cursor: "pointer", fontWeight: 500 },
    list: { display: "flex", flexDirection: "column", gap: 12 },
    card: { background: "#fff", border: "1.5px solid #ededea", borderRadius: 10, padding: "16px 20px", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 20 },
    cardLeft: { display: "flex", gap: 14, flex: 1, minWidth: 0 },
    avatar: { width: 40, height: 40, borderRadius: "50%", background: "#C9A96E18", color: "#C9A96E", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, fontWeight: 500, flexShrink: 0 },
    masterName: { fontSize: 14, fontWeight: 500, color: "#1a1208", marginBottom: 2 },
    masterEmail: { fontSize: 12, color: "#aaa" },
    modTag: { fontSize: 9, padding: "2px 8px", background: "#f0f0ee", borderRadius: 20, color: "#555", letterSpacing: ".04em" },
    cardRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 10, flexShrink: 0 },
    lastSeen: { fontSize: 11, color: "#bbb" },
    editBtn: { fontSize: 10, padding: "5px 12px", border: "1.5px solid #e8e8e4", borderRadius: 5, background: "#fff", cursor: "pointer", color: "#555" },
    revokeBtn: { fontSize: 10, padding: "5px 12px", border: "1.5px solid #d4909044", background: "#d4909018", color: "#9a3030", borderRadius: 5, cursor: "pointer" },
    empty: { textAlign: "center", padding: "60px 0", fontSize: 13, color: "#bbb" },
};
