export const S = {
  page: { padding: "32px 40px", maxWidth: 1200, margin: "0 auto", fontFamily: "'DM Sans',sans-serif" },
  loading: { display: "flex", alignItems: "center", justifyContent: "center", height: "60vh", fontSize: 16, gap: 12, fontFamily: "'DM Sans',sans-serif", color: "#999" },
  toast: { position: "fixed", top: 20, right: 20, zIndex: 999, padding: "12px 20px", borderRadius: 8, color: "#fff", fontSize: 13, fontWeight: 500, boxShadow: "0 4px 20px rgba(0,0,0,.15)" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 32 },
  heading: { fontFamily: "'Cormorant Garamond',serif", fontSize: 32, fontWeight: 400, color: "#1a1208", letterSpacing: "-.01em", marginBottom: 4 },
  sub: { fontSize: 13, color: "#aaa" },
  newBtn: { fontSize: 11, letterSpacing: ".1em", textTransform: "uppercase", padding: "10px 20px", border: "none", borderRadius: 6, fontWeight: 600, textDecoration: "none", cursor: "pointer", flexShrink: 0 },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: 16, marginBottom: 24 },
  statCard: { background: "#fff", borderRadius: 10, padding: "20px 20px 16px", border: "1.5px solid #ededea", display: "flex", flexDirection: "column", gap: 2 },
  statValue: { fontFamily: "'Cormorant Garamond',serif", fontSize: 36, fontWeight: 300, color: "#1a1208", lineHeight: 1, letterSpacing: "-.02em" },
  statLabel: { fontSize: 12, fontWeight: 500, color: "#555", marginTop: 6 },
  statSub: { fontSize: 11, color: "#bbb" },
  twoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 },
  card: { background: "#fff", borderRadius: 10, border: "1.5px solid #ededea", overflow: "hidden", marginBottom: 16 },
  cardHead: { padding: "16px 20px", borderBottom: "1px solid #f0f0ee", display: "flex", alignItems: "center", justifyContent: "space-between" },
  cardTitle: { fontFamily: "'Cormorant Garamond',serif", fontSize: 18, fontWeight: 400, color: "#1a1208" },
  cardLink: { fontSize: 12, textDecoration: "none", letterSpacing: ".04em" },
  catBtn: { fontSize: 10, padding: "4px 9px", border: "1.5px solid #e8e8e4", borderRadius: 5, background: "#fff", cursor: "pointer", color: "#555", textDecoration: "none", letterSpacing: ".03em", whiteSpace: "nowrap", fontFamily: "'DM Sans',sans-serif" },
  empty: { padding: "20px", fontSize: 13, color: "#bbb", textAlign: "center" },
  approvalRow: { display: "flex", alignItems: "center", gap: 12, padding: "11px 20px", borderBottom: "1px solid #f5f5f2" },
  typePill: { fontSize: 9, letterSpacing: ".1em", textTransform: "uppercase", padding: "2px 7px", borderRadius: 3, fontWeight: 600, flexShrink: 0 },
  approvalInfo: { flex: 1, minWidth: 0 },
  approvalTitle: { display: "block", fontSize: 13, fontWeight: 400, color: "#1a1208", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  approvalMeta: { fontSize: 11, color: "#bbb" },
  approveBtn: { fontSize: 12, padding: "4px 9px", borderRadius: 5, cursor: "pointer", fontWeight: 600 },
  activityRow: { display: "flex", gap: 12, padding: "11px 20px", borderBottom: "1px solid #f5f5f2", alignItems: "flex-start" },
  activityDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0, marginTop: 5 },
  activityAction: { fontSize: 12, fontWeight: 500, color: "#1a1208" },
  activityTarget: { fontSize: 12, color: "#666" },
  activityMeta: { fontSize: 10, color: "#bbb", marginTop: 2 },
  liveNote: { fontSize: 11, color: "#7ec87e", fontWeight: 500 },
  flagsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 0 },
  flagRow: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 20px", borderBottom: "1px solid #f5f5f2" },
  flagLabel: { fontSize: 12, color: "#555" },
  toggle: { width: 38, height: 22, borderRadius: 11, border: "none", cursor: "pointer", position: "relative", transition: "background .2s", flexShrink: 0 },
  toggleThumb: { position: "absolute", top: 2, width: 18, height: 18, borderRadius: "50%", background: "#fff", transition: "transform .2s", boxShadow: "0 1px 4px rgba(0,0,0,0.2)" },
};
